### ISSUE TITLE
tqdm dependency error

### ISSUE THREAD

**Issue by kaulfusa** [NASA-IMPACT/csdap-bulk-download#19]
ModuleNotFoundError: No module named 'tqdm.contrib.logging'

![image](https://user-images.githubusercontent.com/43527413/154400996-4f4b7f28-5e70-4db6-9fa2-9e4c9bc03876.png)

**Comment by alukach** [comment]
It looks like `tqdm.contrib.logging` was added in [v4.60.0](https://github.com/tqdm/tqdm/tree/v4.60.0/tqdm/contrib/logging) (was unavailable in [v4.59.0](https://github.com/tqdm/tqdm/tree/v4.59.0/tqdm/contrib/logging).  My guess is the user had an older version of `tqdm` on their machine already and because we don't specify a minimum version, it was updated upon install.

For an immediate fix, the user should be able to run `pip install tqdm>=v4.60.0`.  For a longer term fix, we will pin the version in our `setup.py` file.
